# Generated by Django 5.2 on 2025-04-15 08:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Segnalato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno_nascita', models.PositiveIntegerField(help_text='Inserisci un anno valido (es. 2002, 2015).', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('numero_maglia', models.PositiveIntegerField()),
                ('squadra', models.CharField(max_length=100)),
                ('descrizione_match', models.TextField(help_text='Breve descrizione della partita in cui il giocatore è stato visto.')),
                ('ruolo', models.CharField(choices=[('Portiere', 'Portiere'), ('Difensore', 'Difensore'), ('Centrocampista', 'Centrocampista'), ('Attaccante', 'Attaccante')], max_length=20)),
                ('data_operazione', models.DateTimeField(auto_now_add=True)),
                ('stato', models.CharField(choices=[('Nuova', 'Nuova'), ('In Revisione', 'In Revisione'), ('Approvata', 'Approvata'), ('Scartata', 'Scartata')], default='Nuova', max_length=20)),
                ('descrizione_breve', models.TextField(blank=True, null=True)),
                ('collaboratore', models.ForeignKey(help_text="Collaboratore che ha registrato l'operazione (segnalazione o visione).", null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Giocatore Segnalato',
                'verbose_name_plural': 'Giocatori Segnalati',
            },
        ),
        migrations.CreateModel(
            name='Visionato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno_nascita', models.PositiveIntegerField(help_text='Inserisci un anno valido (es. 2002, 2015).', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('numero_maglia', models.PositiveIntegerField()),
                ('squadra', models.CharField(max_length=100)),
                ('descrizione_match', models.TextField(help_text='Breve descrizione della partita in cui il giocatore è stato visto.')),
                ('ruolo', models.CharField(choices=[('Portiere', 'Portiere'), ('Difensore', 'Difensore'), ('Centrocampista', 'Centrocampista'), ('Attaccante', 'Attaccante')], max_length=20)),
                ('data_operazione', models.DateTimeField(auto_now_add=True)),
                ('descrizione_dettagliata', models.TextField(blank=True, help_text='Descrizione dettagliata fornita dal collaboratore.', null=True)),
                ('telefono_genitore', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Inserisci un numero valido in formato italiano.', regex='^\\+39\\d{9,12}$')])),
                ('collaboratore', models.ForeignKey(help_text="Collaboratore che ha registrato l'operazione (segnalazione o visione).", null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Giocatore Visionato',
                'verbose_name_plural': 'Giocatori Visionati',
            },
        ),
    ]
