# Generated by Django 5.2.4 on 2025-07-05 17:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0003_segnalato_data_segnalazione_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='segnalato',
            name='telefono_genitore',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Inserisci un numero valido in formato italiano.', regex='^\\+39\\d{9,12}$')], verbose_name='Numero cellulare genitore'),
        ),
    ]
