# Generated by Django 5.2 on 2025-07-10 13:22

import django.core.validators
import scouting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0005_visionato_data_revisione_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='segnalato',
            name='note_gara',
            field=models.FileField(blank=True, help_text='Carica un PDF (max 2MB) come Note Gara', null=True, upload_to='note_gara/', validators=[scouting.models.validate_pdf]),
        ),
        migrations.AddField(
            model_name='visionato',
            name='note_gara',
            field=models.FileField(blank=True, help_text='Carica un PDF (max 2MB) come Note Gara', null=True, upload_to='note_gara/', validators=[scouting.models.validate_pdf]),
        ),
        migrations.AlterField(
            model_name='segnalato',
            name='telefono_genitore',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Inserisci un numero valido in formato italiano.', regex='^\\\\+39\\\\d{9,12}$')], verbose_name='Numero cellulare genitore'),
        ),
        migrations.AlterField(
            model_name='visionato',
            name='telefono_genitore',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Inserisci un numero valido in formato italiano.', regex='^\\\\+39\\\\d{9,12}$')], verbose_name='Numero cellulare genitore'),
        ),
    ]
