# Generated by Django 5.2 on 2025-07-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0006_segnalato_note_gara_visionato_note_gara_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.PositiveIntegerField(choices=[(2010, '2010'), (2011, '2011'), (2012, '2012'), (2013, '2013'), (2014, '2014'), (2015, '2015'), (2016, '2016')])),
                ('file', models.FileField(upload_to='note_referti/')),
                ('nome', models.CharField(max_length=255)),
                ('data_caricamento', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
