# Generated by Django 5.2 on 2025-07-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='segnalato',
            name='capacita_cognitiva',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='segnalato',
            name='capacita_fisica',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='segnalato',
            name='cognome',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='segnalato',
            name='nome',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='segnalato',
            name='piede',
            field=models.CharField(blank=True, choices=[('Destro', 'Destro'), ('Sinistro', 'Sinistro')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='segnalato',
            name='struttura_fisica',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visionato',
            name='capacita_cognitiva',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visionato',
            name='capacita_fisica',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visionato',
            name='cognome',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visionato',
            name='nome',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visionato',
            name='piede',
            field=models.CharField(blank=True, choices=[('Destro', 'Destro'), ('Sinistro', 'Sinistro')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='visionato',
            name='struttura_fisica',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
