# Generated by Django 5.2 on 2025-07-04 19:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0002_segnalato_capacita_cognitiva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='segnalato',
            name='data_segnalazione',
            field=models.DateField(default=django.utils.timezone.now, help_text='Data in cui hai visto il giocatore giocare.', verbose_name="Giorno in cui l'hai visto"),
        ),
        migrations.AddField(
            model_name='visionato',
            name='data_segnalazione',
            field=models.DateField(default=django.utils.timezone.now, help_text='Data in cui hai visto il giocatore giocare.', verbose_name="Giorno in cui l'hai visto"),
        ),
        migrations.AlterField(
            model_name='segnalato',
            name='numero_maglia',
            field=models.PositiveIntegerField(help_text='Numero di maglia del giocatore.'),
        ),
        migrations.AlterField(
            model_name='visionato',
            name='numero_maglia',
            field=models.PositiveIntegerField(help_text='Numero di maglia del giocatore.'),
        ),
    ]
