# Generated by Django 5.2.4 on 2025-07-05 17:30

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0004_segnalato_telefono_genitore'),
    ]

    operations = [
        migrations.AddField(
            model_name='visionato',
            name='data_revisione',
            field=models.DateField(default=django.utils.timezone.now, help_text='Data in cui il giocatore è stato convertito da segnalato a visionato.', verbose_name='Data di revisione'),
        ),
        migrations.AlterField(
            model_name='visionato',
            name='telefono_genitore',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Inserisci un numero valido in formato italiano.', regex='^\\+39\\d{9,12}$')], verbose_name='Numero cellulare genitore'),
        ),
    ]
